### ISSUE TITLE
Add and generate code documentation

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Hades252#22]
The code is almost undocumented, we should start to add the docs.

**Comment by CPerezz** [comment]
Should `gadgets.rs` be documented? Since they are only used to test the `blindbid` protocol, and as discussed with @ZER0  and @vlopes11, these tests should be moved to the `dusk-network/blindbid` library and removed from this crate.

So I don't know if it's worth it to comment the `gadgets.rs` file.
